version: 0.6-pre1-{build}
image: Visual Studio 2019 Preview
environment:
  global:
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
clone_depth: 10
init:
- git config --global core.autocrlf true
install:
- ps: |
    Start-FileDownload 'https://download.visualstudio.microsoft.com/download/pr/a46fa009-033b-430d-89a8-c9a107f73d87/d25f962e8212aafb3b0c426eb8cb4dc6/dotnet-sdk-3.0.100-preview8-013656-win-x64.exe'
    Start-Process .\dotnet-sdk-3.0.100-preview8-013656-win-x64.exe "/install /norestart /quiet /log sdkinstall.log" -NoNewWindow -Wait
build_script:
- dotnet build -c Release
test_script:
- dotnet test tests\Sakuno.Base.Tests\Sakuno.Base.Tests.csproj --no-build --configuration Release
after_test:
- ps: Move-Item artifacts\Release\*.nupkg $env:APPVEYOR_BUILD_FOLDER
artifacts:
- path: '*.nupkg'
  name: NuGet
deploy:
- provider: NuGet
  api_key:
    secure: T0e80U98+zD7uGDeVCUG3Y6WKYs850W8zvl6ETJq9QAnWfTSE1gRj7yLWMGfvJ6Z
  skip_symbols: true
