version: 0.6-pre1-{build}
branches:
  only:
  - master
image: Visual Studio 2019 Preview
configuration: Release
platform: Any CPU
init:
- cmd: git config --global core.autocrlf true
nuget:
  disable_publish_on_pr: true
install:
- ps: |
    Start-FileDownload 'https://download.visualstudio.microsoft.com/download/pr/4d2dfaa1-4f9c-4526-bb6f-117d9d8bbd0e/a9fc9994c1b4d485ab41632b81bf4f56/dotnet-sdk-3.0.100-preview6-012264-win-x64.exe'
    Start-Process .\dotnet-sdk-3.0.100-preview6-012264-win-x64.exe "/install /norestart /quiet /log sdkinstall.log" -NoNewWindow -Wait
before_build:
- cmd: nuget restore
build:
  project: Sakuno.Base.sln
  verbosity: minimal
test_script:
- ps: dotnet test tests\Sakuno.Base.Tests\Sakuno.Base.Tests.csproj --configuration Release --no-build /property:Platform=AnyCPU
after_test:
- ps: Move-Item artifacts\$env:configuration\*.nupkg $env:APPVEYOR_BUILD_FOLDER
artifacts:
- path: '*.nupkg'
  name: NuGet
deploy:
- provider: NuGet
  api_key:
    secure: T0e80U98+zD7uGDeVCUG3Y6WKYs850W8zvl6ETJq9QAnWfTSE1gRj7yLWMGfvJ6Z
  skip_symbols: true
