version: 0.6-pre1-{build}
image: Visual Studio 2019
environment:
  global:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: true
clone_depth: 10
init:
- git config --global core.autocrlf true
build_script:
- dotnet build -c Release
test_script:
- dotnet test tests\Sakuno.Base.Tests\Sakuno.Base.Tests.csproj --no-build -c Release
