version: 0.3.2-{build}
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
platform: Any CPU
init:
- cmd: git config --global core.autocrlf true
nuget:
  disable_publish_on_pr: true
before_build:
- cmd: nuget restore
build:
  project: Sakuno.Base.sln
  verbosity: minimal
test:
  assemblies:
    only:
    - artifacts\tests\%configuration%\netcoreapp2.0\Sakuno.Base.Tests.dll
after_test:
- ps: Move-Item artifacts\$($env:configuration)\*.nupkg .
artifacts:
- path: '*.nupkg'
  name: NuGet
deploy:
- provider: NuGet
  api_key:
    secure: uRlrRr17TJpGYMdBG1pTtK/OZws8RkQvrrzgF6lCdXytGjPhsPFXk86qvDzpMkOO
  skip_symbols: true
