name: Sakuno.Base CI
on: [push]
jobs:
  build-and-test:
    name: Build and test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    steps:
    - name: Setup .NET Core 3.0 on macOS
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
      if: matrix.os == 'macos-latest'
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Build Sakuno.Base
      run: dotnet build -c Release
    - name: Test Sakuno.Base
      run: dotnet test -c Release --no-build
