name: Sakuno.Base CI
on: [push]
jobs:
  build-and-test:
    runs-on: windows-latest
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Build Sakuno.Base
      run: dotnet build -c Release
    - name: Test Sakuno.Base
      run: dotnet test -c Release --no-build
